const mongoose = require('mongoose')
const StudyRoom = require('../Models/StudyRoom')
const User = require('../Models/User')
const { notify } = require('./Notification')
const memberQuery = id => ({ $or: [{ owner: id }, { 'members.user': id }] })
const load = (id, user) => StudyRoom.findOne({ _id: id, ...memberQuery(user) }).populate('members.user', 'firstName lastName email').populate('tasks.assignee', 'firstName lastName').populate('notes', 'title')
exports.createRoom = async (req, res) => { try { const room = await StudyRoom.create({ name: String(req.body.name || 'Study room').trim(), owner: req.User.id, members: [{ user: req.User.id, role: 'owner' }] }); return res.status(201).json({ success: true, room }) } catch (e) { return res.status(500).json({ success: false, message: 'Could not create study room' }) } }
exports.listRooms = async (req, res) => { try { const rooms = await StudyRoom.find(memberQuery(req.User.id)).select('name owner members examDate tasks createdAt updatedAt').sort({ updatedAt: -1 }); return res.json({ success: true, rooms }) } catch (e) { return res.status(500).json({ success: false, message: 'Could not load study rooms' }) } }
exports.getRoom = async (req, res) => { try { const room = await load(req.params.id, req.User.id); if (!room) return res.status(404).json({ success: false, message: 'Study room not found' }); const progress = room.members.map(m => ({ user: m.user, assigned: room.tasks.filter(t => String(t.assignee?._id || t.assignee) === String(m.user._id || m.user)).length, completed: room.tasks.filter(t => String(t.assignee?._id || t.assignee) === String(m.user._id || m.user) && t.done).length })); return res.json({ success: true, room, progress }) } catch (e) { return res.status(500).json({ success: false, message: 'Could not load study room' }) } }
exports.addMember = async (req, res) => { try { const room = await StudyRoom.findOne({ _id: req.params.id, owner: req.User.id }); const user = await User.findOne({ email: String(req.body.email || '').toLowerCase().trim() }).select('_id'); if (!room || !user) return res.status(404).json({ success: false, message: 'Room or user not found' }); if (!room.members.some(m => String(m.user) === String(user._id))) room.members.push({ user: user._id }); await room.save(); notify({ user: user._id, type: 'room_invite', message: `You were added to study room "${room.name}".`, link: '/Dashboard/StudyRooms' }); return res.json({ success: true, room }) } catch (e) { return res.status(500).json({ success: false, message: 'Could not add member' }) } }
exports.addTask = async (req, res) => { try { const room = await StudyRoom.findOne({ _id: req.params.id, ...memberQuery(req.User.id) }); if (!room) return res.status(404).json({ success: false, message: 'Study room not found' }); const requestedAssignee = req.body.assignee ? String(req.body.assignee) : String(req.User.id); const assignee = room.members.some(m => String(m.user) === requestedAssignee) ? requestedAssignee : req.User.id; const title = String(req.body.title || '').trim(); room.tasks.push({ title, assignee, dueDate: req.body.dueDate }); await room.save(); notify({ user: assignee, type: 'room_task_assigned', message: `New study-room task in "${room.name}": ${title}`, link: '/Dashboard/StudyRooms' }); return res.json({ success: true, task: room.tasks.at(-1) }) } catch (e) { return res.status(500).json({ success: false, message: 'Could not add task' }) } }
exports.toggleTask = async (req, res) => { try { const room = await StudyRoom.findOne({ _id: req.params.id, ...memberQuery(req.User.id) }); const task = room?.tasks.id(req.params.taskId); if (!task) return res.status(404).json({ success: false, message: 'Task not found' }); task.done = !task.done; task.completedBy = task.done ? req.User.id : null; await room.save(); if (task.done && String(task.assignee) !== String(req.User.id)) notify({ user: task.assignee, type: 'room_task_completed', message: `A study-room task was completed in "${room.name}".`, link: '/Dashboard/StudyRooms' }); return res.json({ success: true, task }) } catch (e) { return res.status(500).json({ success: false, message: 'Could not update task' }) } }
exports.updateCalendar = async (req, res) => { try { const room = await StudyRoom.findOne({ _id: req.params.id, ...memberQuery(req.User.id) }); if (!room) return res.status(404).json({ success: false, message: 'Study room not found' }); room.examDate = new Date(req.body.examDate); await room.save(); return res.json({ success: true, examDate: room.examDate }) } catch (e) { return res.status(500).json({ success: false, message: 'Could not update calendar' }) } }
