const express = require('express')
const route = express.Router()
const { Auth, blockIfBanned } = require('../Middlewares/Auth.js')
const { doubleCsrfProtection } = require('../Middlewares/Csrf.js')
const c = require('../controllers/StudyRoom.js')
route.use(Auth, blockIfBanned)
route.get('/', c.listRooms)
route.post('/', doubleCsrfProtection, c.createRoom)
route.get('/:id', c.getRoom)
route.post('/:id/members', doubleCsrfProtection, c.addMember)
route.post('/:id/tasks', doubleCsrfProtection, c.addTask)
route.patch('/:id/tasks/:taskId', doubleCsrfProtection, c.toggleTask)
route.put('/:id/calendar', doubleCsrfProtection, c.updateCalendar)
module.exports = route
