import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import { apiConnector } from '../../Services/apiConnector.js'
import { Helmet } from 'react-helmet-async'
const url = `${import.meta.env.VITE_MAIN_BACKEND_URL}/study-rooms`
export default function StudyRooms() {
    const { token } = useSelector(s => s.auth); const [rooms, setRooms] = useState([]); const [room, setRoom] = useState(null); const [name, setName] = useState(''); const [task, setTask] = useState(''); const [email, setEmail] = useState(''); const [examDate, setExamDate] = useState('')
    const headers = { Authorization: `Bearer ${token}` }
    const loadRooms = async () => { const r = await apiConnector('GET', url, null, headers); setRooms(r.data.rooms || []) }
    useEffect(() => { loadRooms() }, [token])
    const open = async id => { const r = await apiConnector('GET', `${url}/${id}`, null, headers); setRoom(r.data) }
    const create = async e => { e.preventDefault(); const r = await apiConnector('POST', url, { name }, headers); setName(''); loadRooms(); setRoom(r.data) }
    const addTask = async e => { e.preventDefault(); const r = await apiConnector('POST', `${url}/${room.room._id}/tasks`, { title: task }, headers); setTask(''); setRoom({ ...room, room: { ...room.room, tasks: [...room.room.tasks, r.data.task] } }) }
    const addMember = async e => { e.preventDefault(); await apiConnector('POST', `${url}/${room.room._id}/members`, { email }, headers); setEmail(''); open(room.room._id) }
    const toggle = async id => { await apiConnector('PATCH', `${url}/${room.room._id}/tasks/${id}`, null, headers); open(room.room._id) }
    const saveDate = async e => { setExamDate(e.target.value); await apiConnector('PUT', `${url}/${room.room._id}/calendar`, { examDate: e.target.value }, headers) }
    return <><Helmet><title>Study rooms — Notewise</title></Helmet><div className="max-w-5xl mx-auto px-4 py-8"><h1 className="text-xl font-bold text-richblack-5">Shared study rooms</h1><p className="text-richblack-400 text-sm mb-6">Assign work, track progress, and prepare for an exam together.</p><form onSubmit={create} className="flex gap-2 mb-6"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Room name" className="flex-1 bg-surface border border-border-soft rounded px-3 py-2 text-richblack-5"/><button className="bg-yellow-50 text-richblack-900 px-4 rounded font-semibold">Create room</button></form><div className="grid md:grid-cols-3 gap-4">{rooms.map(r=><button type="button" key={r._id} onClick={()=>open(r._id)} className="text-left border border-border-soft bg-surface rounded p-4 text-richblack-5">{r.name}<p className="text-xs text-richblack-400 mt-2">{r.members?.length || 0} members · {r.tasks?.filter(t=>t.done).length || 0}/{r.tasks?.length || 0} tasks</p></button>)}</div>{room&&<div className="mt-8 border border-violet-400/40 bg-surface rounded-lg p-5"><h2 className="font-semibold text-richblack-5 mb-4">{room.room.name}</h2><div className="flex flex-wrap gap-3 mb-4"><form onSubmit={addMember} className="flex gap-2"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Member email" className="bg-surface-raised border border-border-soft rounded px-2 py-1 text-sm"/><button className="text-yellow-50 text-sm">Invite</button></form><label className="text-sm text-richblack-300">Exam date <input type="date" value={examDate || (room.room.examDate ? room.room.examDate.slice(0,10) : '')} onChange={saveDate} className="ml-2 bg-surface-raised border border-border-soft rounded px-2 py-1"/></label></div><form onSubmit={addTask} className="flex gap-2 mb-4"><input required value={task} onChange={e=>setTask(e.target.value)} placeholder="Assign a study task" className="flex-1 bg-surface-raised border border-border-soft rounded px-3 py-2 text-sm text-richblack-5"/><button className="bg-yellow-50 text-richblack-900 px-3 rounded font-semibold text-sm">Assign</button></form><div className="space-y-2">{room.room.tasks.map(t=><button type="button" key={t._id} onClick={()=>toggle(t._id)} className={`w-full text-left border rounded px-3 py-2 text-sm ${t.done?'border-good/50 text-good':'border-border-soft text-richblack-200'}`}>{t.done?'✓ ':''}{t.title}</button>)}</div><h3 className="font-semibold text-richblack-5 mt-6 mb-2">Member progress</h3>{room.progress.map(p=><p key={p.user._id} className="text-sm text-richblack-300">{p.user.firstName} {p.user.lastName}: {p.completed}/{p.assigned} tasks complete</p>)}</div>}</div></>
}
