export const SUMMARIZER_EXPLAINERS = {
    text: {
        label: 'Text',
        title: 'What Is an AI Text Summarizer?',
        body: "An AI Text Summarizer reads any block of text you paste in — meeting notes, lecture notes, or freeform thoughts — and condenses it into a clear, structured summary in seconds. Simply paste your text and receive a TL;DR, key points, and action items without re-reading the whole thing.",
        howTitle: 'AI Text Summarizer',
        howSubtitle: 'Summarizing any text with our AI tool is fast and straightforward',
        steps: [
            { title: 'Paste Your Text', body: 'Copy and paste any text content directly into the tool — articles, essays, emails, reports, or any written content. No file uploads needed.' },
            { title: 'AI Analyzes the Content', body: 'Our AI reads the entire text, identifies key themes, arguments, and essential details, and determines what matters most from your content.' },
            { title: 'Receive Your Summary Instantly', body: 'In seconds, receive a well-organized summary that captures the core message and important takeaways from your text — ready to use right away.' },
        ],
        useCasesTitle: 'AI Text Summarizer',
        useCases: [
            { icon: 'article', title: 'Articles and Blog Posts', body: 'Summarize news articles and blog posts into concise summaries with key points using the AI text summarizer.' },
            { icon: 'edit', title: 'Essays and Academic Writing', body: 'Run essays and academic content through the AI text summarizer to capture the core thesis and findings.' },
            { icon: 'mail', title: 'Emails and Business Communication', body: 'Condense lengthy email threads and memos into clear, actionable summaries with the AI text summarizer.' },
            { icon: 'book', title: 'Reports and Documents', body: 'Summarize business reports and project updates to extract the most important data using the AI text summarizer.' },
            { icon: 'notes', title: 'Meeting Notes and Transcripts', body: 'Turn raw meeting notes and transcripts into organized summaries with key decisions using the AI text summarizer.' },
            { icon: 'social', title: 'Social Media and Online Content', body: 'Summarize long social media threads and forum discussions to get key information with the AI text summarizer.' },
        ],
        whyTitle: 'AI Text Summarizer',
        whyBenefits: [
            { icon: 'notes', title: 'Summarize Any Type of Text', body: 'Our AI text summarizer works with any written content — articles, essays, reports, emails, blog posts, meeting notes, and more. No matter the length or complexity, it delivers a focused summary.' },
            { icon: 'accurate', title: 'Get to the Key Points Faster', body: 'Stop spending time reading through walls of text. Our AI text summarizer pulls out the most important ideas, arguments, and conclusions so you understand the core message quickly.' },
            { icon: 'formats', title: 'Choose Your Summary Length', body: 'Need a one-paragraph overview or a detailed multi-point summary? Our AI text summarizer lets you control the output length so you get exactly the level of detail you need.' },
            { icon: 'accurate2', title: 'Accurate and Meaningful Summaries', body: 'Our AI goes beyond simple sentence extraction. It understands context, identifies relationships between ideas, and generates summaries that are coherent, readable, and meaningful.' },
            { icon: 'lang', title: 'Supports Multiple Languages', body: "Our AI text summarizer can process and summarize text in multiple languages, allowing you to summarize content regardless of the language it's written in." },
            { icon: 'star', title: '100% Free with No Sign-Up', body: 'Use our AI text summarizer completely free of charge. Paste and summarize as much text as you want without creating an account or paying for any subscription.' },
        ],
        whoBenefitsTitle: 'AI Text Summarizer',
        whoBenefits: [
            { title: 'Students and Educators', body: 'Summarize lecture notes, textbook chapters, and academic content into quick, easy-to-review study materials for faster learning and exam preparation.' },
            { title: 'Writers and Bloggers', body: 'Condense research and reference content into brief summaries to streamline the writing process and speed up content creation workflows.' },
            { title: 'Marketers and SEO Professionals', body: 'Summarize competitor content, industry articles, and campaign reports to extract actionable insights faster and inform your strategy.' },
            { title: 'Business Professionals', body: 'Get concise summaries of emails, memos, proposals, and internal communications to save time and improve productivity every day.' },
            { title: 'Researchers and Analysts', body: 'Quickly summarize large volumes of text-based data, literature, and publications to accelerate the research and analysis process.' },
            { title: 'Everyday Users', body: 'Summarize news articles, social media threads, or any long-form text to get the key information without reading everything from start to finish.' },
        ],
        faqs: [
            { q: 'What kind of text can I summarize?', a: 'Anything you can paste as plain text — articles, essays, emails, meeting notes, reports, or freeform thoughts. There is no restriction on topic.' },
            { q: 'Is there a length limit for the text I can summarize?', a: 'Very long pastes are supported, though extremely long text may take a little longer to process and use more of your monthly credits on Pro/Pro Max plans.' },
            { q: 'Can I choose how detailed the summary is?', a: 'Yes — your plan controls depth. Basic gives you a TL;DR and key points; Pro adds sections and key terms; Pro Max adds quiz and flashcard generation on top.' },
            { q: 'Is the AI text summarizer free?', a: 'Yes, the Basic plan is free and includes 5 summaries a month at no cost, across text, document, and article inputs.' },
            { q: 'How accurate are the text summaries?', a: 'Summaries are generated by an LLM grounded strictly in the text you provide, so accuracy depends on how clear the source text is — the model does not add outside information.' },
            { q: 'How is this different from the Document Summarizer?', a: 'Same underlying pipeline — the Document tab just extracts text from an uploaded PDF/DOCX/TXT file first, then runs the identical summarization step.' },
        ],
    },
    document: {
        label: 'Document',
        title: 'What Is an AI Document Summarizer?',
        body: "An AI Document Summarizer is a versatile tool that reads, analyzes, and summarizes any document — regardless of format — into a clear, concise summary in seconds. Simply upload your PDF, Word, or TXT file and receive an accurate summary that captures the key points, critical findings, and essential takeaways without reading every page.",
        howTitle: 'AI Document Summarizer',
        howSubtitle: 'Summarizing any document is quick and effortless with our AI tool',
        steps: [
            { title: 'Upload Your Document', body: 'Drag and drop or browse to upload any document file. Our tool supports PDF, DOCX, and TXT formats.' },
            { title: 'AI Reads and Analyzes', body: 'Our AI scans the entire file, identifies key sections, extracts important information, and understands the overall context and structure of your document.' },
            { title: 'Get Your Summary Instantly', body: 'Within seconds, receive a clean, organized summary highlighting the main ideas, critical data, and key conclusions from your document.' },
        ],
        useCasesTitle: 'AI Document Summarizer',
        useCases: [
            { icon: 'formats', title: 'Supports Multiple Document Formats', body: 'Our AI document summarizer handles PDFs, Word documents, and text files — all from a single tool.' },
            { icon: 'time', title: 'Save Hours of Reading Time', body: 'Long documents can take hours to review. Our summarizer condenses the most important information into a brief, scannable summary.' },
            { icon: 'accurate', title: 'Accurate and Format-Aware Summaries', body: 'Our AI understands document structures including headings, sections, and bullet points to generate smarter, organized summaries.' },
            { icon: 'notes', title: 'Handles Long, Multi-Page Files', body: 'Whether it is a 5-page memo or a 100-page report, the summarizer scales to any document length without losing the key points.' },
            { icon: 'book', title: 'Reports and Research Papers', body: 'Summarize business reports, whitepapers, and research documents to extract findings without reading every page.' },
            { icon: 'star', title: 'Included on Every Plan', body: 'Document summarization is available on every plan, including Basic — no extra add-on required to get started.' },
        ],
        whyTitle: 'AI Document Summarizer',
        whyBenefits: [
            { icon: 'notes', title: 'Business Professionals', body: 'Summarize reports, proposals, and strategy documents to stay productive and make faster, more informed decisions every day.' },
            { icon: 'lecture', title: 'Students and Academics', body: 'Condense research papers, study guides, and course materials into quick, effective study notes for faster learning and exam preparation.' },
            { icon: 'book', title: 'Lawyers and Legal Teams', body: 'Summarize contracts, case files, and compliance documents to identify critical clauses, terms, and obligations efficiently.' },
            { icon: 'formats', title: 'HR and Admin Teams', body: 'Create quick summaries of policy documents, training manuals, and employee handbooks for easy team reference and onboarding.' },
            { icon: 'accurate', title: 'Researchers and Analysts', body: 'Process and summarize large volumes of documents, publications, and data reports to accelerate your research and analysis workflow.' },
            { icon: 'edit', title: 'Freelancers and Consultants', body: 'Review client documents, project briefs, and industry reports faster to understand key details and deliver work more efficiently.' },
        ],
        whoBenefitsTitle: 'AI Document Summarizer',
        whoBenefits: [
            { title: 'Business Professionals', body: 'Summarize reports, proposals, and strategy documents to stay productive and make faster, more informed decisions every day.' },
            { title: 'Students and Academics', body: 'Condense research papers, study guides, and course materials into quick, effective study notes for faster learning and exam preparation.' },
            { title: 'Lawyers and Legal Teams', body: 'Summarize contracts, case files, and compliance documents to identify critical clauses, terms, and obligations efficiently.' },
            { title: 'HR and Admin Teams', body: 'Create quick summaries of policy documents, training manuals, and employee handbooks for easy team reference and onboarding.' },
            { title: 'Researchers and Analysts', body: 'Process and summarize large volumes of documents, publications, and data reports to accelerate your research and analysis workflow.' },
            { title: 'Freelancers and Consultants', body: 'Review client documents, project briefs, and industry reports faster to understand key details and deliver work more efficiently.' },
        ],
        faqs: [
            { q: 'What document formats does the summarizer support?', a: 'PDF, Word (.docx), and plain text (.txt) files, up to 10MB per upload.' },
            { q: 'Can I summarize long documents?', a: 'Yes — the summarizer reads the entire file before generating a summary, whether it is a short memo or a lengthy report.' },
            { q: 'Does it preserve the structure of the document?', a: 'The AI identifies headings and sections while reading, and Pro/Pro Max plans include a structured "Sections & key terms" breakdown in the output.' },
            { q: 'Can it handle scanned documents?', a: 'Not currently — the summarizer reads embedded text, so a scanned image-only PDF with no text layer will not extract correctly.' },
            { q: 'Is the AI document summarizer free?', a: 'Yes, document summarization is included on the free Basic plan, with 5 summaries a month.' },
            { q: 'How is this different from the Text Summarizer?', a: 'The Document tab extracts text from your uploaded file first; everything after that — the AI summarization step — is identical to the Text tab.' },
        ],
    },
    article: {
        label: 'Article',
        title: 'What Is an AI Article Summarizer?',
        body: "An AI Article Summarizer is an intelligent tool that reads, analyzes, and condenses any article into a short, well-structured summary in seconds. Simply paste the article text or its URL and receive an accurate summary that captures the most important points, arguments, and conclusions — without reading the full article.",
        howTitle: 'AI Article Summarizer',
        howSubtitle: 'Summarizing any article is quick and effortless with our AI tool',
        steps: [
            { title: 'Paste the Article URL', body: 'Simply enter the article URL directly into the tool — our AI fetches and processes the content automatically.' },
            { title: 'AI Reads and Analyzes', body: 'Our AI scans the full article, identifies key arguments, supporting points, critical data, and essential takeaways from the entire content.' },
            { title: 'Get Your Summary Instantly', body: 'Within seconds, receive a clean, organized summary that highlights everything important from the article — ready to read and use right away.' },
        ],
        useCasesTitle: 'AI Article Summarizer',
        useCases: [
            { icon: 'article', title: 'News Articles', body: 'Summarize breaking news, political analysis, and current affairs articles to stay informed on the latest headlines in minutes.' },
            { icon: 'edit', title: 'Blog Posts and Online Content', body: 'Condense lengthy blog posts, opinion pieces, and online publications into concise summaries with the key ideas highlighted.' },
            { icon: 'formats', title: 'Industry and Market Reports', body: 'Get quick summaries of industry news, market analysis, and business articles to extract actionable insights without reading every detail.' },
            { icon: 'book', title: 'Academic and Journal Articles', body: 'Summarize academic publications, journal articles, and scholarly content to quickly understand key findings, arguments, and conclusions.' },
            { icon: 'notes', title: 'How-To Guides and Tutorials', body: 'Extract the essential steps, tips, and instructions from lengthy how-to articles and tutorial content without scrolling through filler.' },
            { icon: 'social', title: 'Opinion and Editorial Pieces', body: 'Get the core arguments, perspectives, and conclusions from opinion pieces and editorials in a brief, easy-to-digest summary format.' },
        ],
        whyTitle: 'AI Article Summarizer',
        whyBenefits: [
            { icon: 'notes', title: 'Summarize Any Type of Article', body: 'Our AI article summarizer works with all types of articles — news stories, blog posts, opinion pieces, feature articles, how-to guides, industry reports, and more — regardless of topic or length.' },
            { icon: 'accurate', title: 'Stay Informed Without Information Overload', body: 'The internet is flooded with content. Our AI article summarizer helps you cut through the noise by pulling out the key points from any article so you stay updated quickly.' },
            { icon: 'formats', title: 'Supports URL-Based Summarization', body: "Don't want to copy and paste the full article? Simply enter the article URL and our AI will fetch the content, analyze it, and generate a summary automatically." },
            { icon: 'accurate2', title: 'Accurate and Context-Aware Summaries', body: "Our AI understands the article's structure, identifies the core arguments, and generates a coherent summary that reflects the original content accurately and meaningfully." },
            { icon: 'lang', title: 'Supports Multiple Languages', body: 'Our AI article summarizer can process and summarize articles in multiple languages, allowing you to summarize content from publications around the world.' },
            { icon: 'star', title: '100% Free with No Sign-Up', body: 'Use our AI article summarizer for free with no hidden fees, no subscriptions, and no account creation required. Summarize as many articles as you want, anytime.' },
        ],
        whoBenefitsTitle: 'AI Article Summarizer',
        whoBenefits: [
            { title: 'Students and Academics', body: 'Summarize academic articles, journal papers, and online resources to build study notes, literature reviews, and research references faster.' },
            { title: 'Journalists & Editors', body: 'Quickly summarize competing publications, press releases, and source articles to streamline the reporting and editorial process.' },
            { title: 'Content Creators & Bloggers', body: 'Condense reference articles and trending content into brief summaries for research, content ideation, and creative inspiration.' },
            { title: 'Marketers & SEO Professionals', body: 'Summarize competitor blog posts, industry news, and campaign reports to extract actionable insights and stay ahead of the competition.' },
            { title: 'Business Professionals', body: 'Stay informed on industry trends, leadership articles, and market analysis without dedicating hours of your day to reading every article.' },
            { title: 'Everyday Readers', body: 'Summarize news articles, opinion pieces, and long-form features to get the key information quickly and efficiently without reading everything.' },
        ],
        faqs: [
            { q: 'What types of articles can I summarize?', a: 'Any publicly readable webpage — news articles, blog posts, opinion pieces, and long-form guides.' },
            { q: 'Can I summarize an article by pasting its URL?', a: "Yes — paste the article's link and we fetch and extract its readable content automatically before summarizing." },
            { q: 'Does it work on paywalled articles?', a: 'Not reliably — if a page is behind a login or paywall, the extractor may not be able to reach the article text.' },
            { q: 'Is the AI article summarizer free?', a: 'Yes, article summarization is included on the free Basic plan alongside text and document summaries.' },
            { q: 'How accurate are the article summaries?', a: "Accuracy depends on how cleanly the page's article text can be extracted — heavily ad-laden or JavaScript-rendered pages can occasionally extract incompletely." },
            { q: 'How is this different from the Text Summarizer?', a: 'The Article tab fetches and extracts the page content for you first; the summarization step afterward is the same pipeline used for pasted text.' },
        ],
    },
    youtube: {
        label: 'YouTube',
        title: 'What Is an AI YouTube Video Summarizer?',
        body: "An AI YouTube Video Summarizer is an intelligent tool that analyzes any YouTube video and generates a concise, accurate summary in seconds. Simply paste the video URL and receive a well-structured summary that captures all the key points, main arguments, and essential takeaways — without watching the entire video.",
        howTitle: 'AI YouTube Video Summarizer',
        howSubtitle: 'Summarizing any YouTube video is fast and straightforward',
        steps: [
            { title: 'Paste the YouTube Video URL', body: 'Copy the link of any YouTube video you want to summarize and paste it directly into the tool — no downloads or uploads required.' },
            { title: 'AI Analyzes the Video Content', body: "Our AI processes the video's transcript, identifies key topics, important discussions, and extracts the most relevant information automatically." },
            { title: 'Get Your Summary Instantly', body: 'Within seconds, receive a clean, easy-to-read summary covering all the major points and essential takeaways from the video.' },
        ],
        useCasesTitle: 'AI YouTube Video',
        useCases: [
            { icon: 'lecture', title: 'Educational Lectures', body: 'Summarize university lectures and academic talks to capture key concepts with the AI YouTube video summarizer.' },
            { icon: 'mic', title: 'Tutorials and How-To Videos', body: 'Get essential steps and instructions from tutorial videos using the AI YouTube video summarizer.' },
            { icon: 'waveform', title: 'Podcasts and Interviews', body: 'Extract key discussions and insights from podcast and interview videos with the AI YouTube video summarizer.' },
            { icon: 'chat', title: 'Webinars and Conference Talks', body: 'Summarize keynote speeches and conference presentations using the AI YouTube video summarizer.' },
            { icon: 'news', title: 'News and Analysis Videos', body: 'Get key facts and takeaways from news and current affairs videos with the AI YouTube video summarizer.' },
            { icon: 'review', title: 'Product Reviews and Comparisons', body: 'Extract key pros, cons, and recommendations from review videos using the AI YouTube video summarizer.' },
        ],
        whyTitle: 'AI Youtube Summarizer',
        whyBenefits: [
            { icon: 'youtube', title: 'Summarize Any YouTube Video', body: 'Our AI YouTube video summarizer works with any publicly available YouTube video — tutorials, lectures, podcasts, interviews, reviews, webinars, and more — regardless of length or topic.' },
            { icon: 'time', title: 'Save Hours of Watching Time', body: 'Not every video requires your full attention. Our AI YouTube video summarizer lets you quickly scan the key points before deciding whether to watch the full video.' },
            { icon: 'accurate', title: 'Accurate and Reliable Summaries', body: "Our AI doesn't just cut content short — it intelligently identifies the core ideas, arguments, and conclusions to deliver summaries that truly reflect the video's content." },
            { icon: 'length', title: 'Works with Any Video Length', body: "Whether it's a 5-minute tutorial or a 3-hour lecture, our AI YouTube video summarizer processes videos of any length and delivers a comprehensive summary every time." },
            { icon: 'lang', title: 'Supports Multiple Languages', body: 'Our AI can process and summarize YouTube videos in multiple languages, making it a versatile tool for users watching content from creators around the world.' },
            { icon: 'star', title: '100% Free with No Sign-Up', body: 'Access the AI YouTube video summarizer at no cost. Summarize as many YouTube videos as you need without any hidden fees, subscriptions, or account creation.' },
        ],
        whoBenefitsTitle: 'AI YouTube Video Summarizer',
        whoBenefits: [
            { title: 'Students', body: 'Summarize online lectures, tutorials, and educational videos to create quick study notes and prepare for exams more efficiently.' },
            { title: 'Content Creators', body: 'Research competitor videos and trending topics faster by summarizing multiple YouTube videos in minutes instead of hours.' },
            { title: 'Professionals & Entrepreneurs', body: 'Summarize webinars, keynotes, and industry talks to stay informed and make better decisions without sacrificing productivity.' },
            { title: 'Journalists & Researchers', body: 'Extract key information from interviews, press conferences, and documentary videos to speed up reporting and research workflows.' },
            { title: 'Marketers and SEO Professionals', body: 'Analyze competitor video content and trending topics by summarizing videos quickly to inform your content strategy and campaigns.' },
            { title: 'Casual Viewers', body: 'Decide whether a video is worth watching by reading a quick AI-generated summary first — saving your time for the videos that matter most.' },
        ],
        faqs: [
            { q: 'Can I summarize any YouTube video?', a: "This is coming soon — we're building support for pulling a video's transcript so it can feed into the same summarizer used for text and documents." },
            { q: 'Will I need to download the video first?', a: 'No — once live, you will just paste the video URL. No downloads or uploads will be required.' },
            { q: 'Will it work on videos with no captions?', a: 'Videos without any captions will be harder to support at first, since transcript availability is what makes this fast — that edge case will be addressed as the feature develops.' },
            { q: 'Will it be free?', a: 'Yes — it will be part of the same credit system as the other summarizer tabs, no separate paywall planned.' },
            { q: 'When will this be available?', a: "We're actively working on it. Check back soon, or keep an eye on the other tabs which are already live." },
            { q: 'How will this differ from the Video Summarizer?', a: 'The YouTube tab will work from a pasted URL and the video\'s existing captions; the Video tab will require uploading a file and extracting audio directly.' },
        ],
    },
    video: {
        label: 'Video',
        title: 'What Is an AI Video Summarizer?',
        body: "An AI Video Summarizer uses artificial intelligence to analyze any video file and generate a clear, concise summary in seconds. Simply upload your video and receive a well-structured summary that highlights the key points, main ideas, and critical takeaways — without watching the entire recording.",
        howTitle: 'AI Video Summarizer',
        howSubtitle: 'Summarizing any video takes just a few simple steps',
        steps: [
            { title: 'Upload Your Video File', body: 'Drag and drop or browse to upload any video file from your device. Our tool supports MP4, AVI, MOV, MKV, WebM, and other popular formats.' },
            { title: 'AI Processes the Content', body: 'Our AI extracts the audio, analyzes the transcript, identifies key topics, and pulls out the most relevant information from the entire video.' },
            { title: 'Receive Your Summary Instantly', body: 'In seconds, get a structured, easy-to-read summary capturing all the essential points and critical takeaways from your video.' },
        ],
        useCasesTitle: 'AI Video Summarizer',
        useCases: [
            { icon: 'lecture', title: 'Meeting Recordings', body: 'Summarize recorded meetings into key decisions and action items with the AI video summarizer.' },
            { icon: 'mic', title: 'Training and Tutorial Videos', body: 'Extract essential steps and instructions from training videos using the AI video summarizer.' },
            { icon: 'waveform', title: 'Lectures and Course Videos', body: 'Turn recorded lectures into concise study notes with key concepts using the AI video summarizer.' },
            { icon: 'chat', title: 'Interviews and Testimonials', body: 'Summarize recorded interviews and testimonials to extract key insights with the AI video summarizer.' },
            { icon: 'news', title: 'Conference and Event Recordings', body: 'Get key highlights from conference talks and event sessions using the AI video summarizer.' },
            { icon: 'social', title: 'Personal and Social Media Videos', body: 'Summarize personal recordings and social media videos to review key moments with the AI video summarizer.' },
        ],
        whyTitle: 'AI Video Summarizer',
        whyBenefits: [
            { icon: 'formats', title: 'Supports Multiple Video Formats', body: 'Our AI video summarizer works with a wide range of file types including MP4, AVI, MOV, MKV, WebM, and more — so you never have to worry about format compatibility.' },
            { icon: 'time', title: 'Save Time on Long Videos', body: 'Stop wasting hours watching videos that could be summarized in minutes. Our AI video summarizer extracts the essential information so you can focus on what matters most.' },
            { icon: 'accurate', title: 'Accurate and Context-Aware Summaries', body: 'Our AI goes beyond basic transcription. It understands context, identifies themes, and organizes the summary logically to ensure you get a meaningful overview of any video.' },
            { icon: 'length', title: 'Works with Any Video Length', body: 'Whether it is a short 2-minute clip or a multi-hour recording, our AI video summarizer processes videos of any length and delivers a comprehensive summary every time.' },
            { icon: 'lang', title: 'Supports Multiple Languages', body: 'Our AI video summarizer can process and summarize videos in multiple languages, making it a versatile tool for users working with content from around the world.' },
            { icon: 'star', title: '100% Free with No Sign-Up', body: 'Access our AI video summarizer for free. Upload and summarize as many videos as you need without creating an account, paying fees, or subscribing.' },
        ],
        whoBenefitsTitle: 'AI Video Summarizer',
        whoBenefits: [
            { title: 'Students', body: 'Summarize recorded lectures, online courses, and educational videos into quick, digestible study notes for faster exam preparation.' },
            { title: 'Business Professionals', body: 'Get concise summaries of recorded meetings, presentations, and corporate training videos to stay aligned without rewatching.' },
            { title: 'Content Creators', body: 'Quickly review and break down long-form video content for repurposing into blogs, social posts, or short-form videos.' },
            { title: 'Journalists & Researchers', body: 'Extract key information from interviews, documentaries, and press events without watching every minute of footage.' },
            { title: 'Legal and Compliance Teams', body: 'Summarize depositions, recorded testimonies, and compliance training videos for faster review and documentation.' },
            { title: 'Project Managers', body: 'Summarize recorded sprint reviews, stakeholder meetings, and project updates to share key takeaways with your team quickly.' },
        ],
        faqs: [
            { q: 'What video formats will be supported?', a: 'We plan to support common formats like MP4, MOV, and WebM once this feature ships.' },
            { q: 'Can I summarize long videos?', a: 'That is the goal — this feature is still under development, so exact length limits have not been finalized yet.' },
            { q: 'Is the AI video summarizer free to use?', a: 'It will be part of the same credit system as the rest of the app — no separate charge planned.' },
            { q: 'How will it process the video?', a: 'The plan is to extract the audio track from your uploaded video and transcribe it, then run the same summarization pipeline used elsewhere in the app.' },
            { q: 'How is this different from the YouTube Video Summarizer?', a: 'This tab is for uploading your own video file directly; the YouTube tab will work from a pasted link to a publicly hosted video instead.' },
            { q: 'When will this be available?', a: "We're actively building it — audio transcription (used by the Audio tab) is live today, and video support builds on that same foundation." },
        ],
    },
    audio: {
        label: 'Audio',
        title: 'What Is an AI Audio Summarizer?',
        body: "An AI Audio Summarizer is a powerful tool that listens to, transcribes, and summarizes any audio file into a clear, concise summary in seconds. Simply upload your audio recording and receive an accurate summary that captures all the key points, important discussions, and essential details — without listening to the entire file.",
        howTitle: 'AI Audio Summarizer',
        howSubtitle: 'Summarizing any audio recording with our AI tool takes just a few simple steps',
        steps: [
            { title: 'Upload Your Audio File', body: 'Drag and drop or browse to upload any audio file in popular formats like MP3, WAV, M4A, OGG, FLAC, and more directly from your device.' },
            { title: 'AI Listens and Analyzes', body: 'Our AI transcribes the audio, identifies key topics, important discussions, and essential takeaways from the entire recording automatically.' },
            { title: 'Get Your Summary Instantly', body: 'Within seconds, receive a structured, easy-to-read summary covering all the major points and critical information from your audio content.' },
        ],
        useCasesTitle: 'AI Audio Summarizer',
        useCases: [
            { icon: 'lecture', title: 'Podcast Episodes', body: 'Summarize your favorite podcast episodes to review key highlights and discussions with the AI audio summarizer.' },
            { icon: 'mic', title: 'Meeting Recordings', body: 'Turn recorded meetings into concise summaries of key decisions and action items using the AI audio summarizer.' },
            { icon: 'waveform', title: 'Lecture Recordings', body: 'Run recorded lectures through the AI audio summarizer to create quick study notes with key concepts and takeaways.' },
            { icon: 'chat', title: 'Interviews and Conversations', body: 'Extract key quotes, insights, and details from recorded interviews and calls with the AI audio summarizer.' },
            { icon: 'news', title: 'Conference Calls and Webinars', body: 'Get essential highlights from conference calls and webinar recordings using the AI audio summarizer.' },
            { icon: 'edit', title: 'Voice Memos and Personal Notes', body: 'Convert voice memos and audio notes into clear, organized text summaries with the AI audio summarizer.' },
        ],
        whyTitle: 'AI Audio Summarizer',
        whyBenefits: [
            { icon: 'audio', title: 'Supports All Popular Audio Formats', body: 'Our AI audio summarizer works with a wide range of audio file types including MP3, WAV, M4A, OGG, FLAC, and more — no format conversions needed.' },
            { icon: 'time', title: 'Save Hours of Listening Time', body: 'Long audio recordings can eat up your entire day. Our AI audio summarizer condenses hours of audio into a brief, scannable summary you can review in minutes.' },
            { icon: 'accurate', title: 'Accurate Transcription and Summarization', body: "Our AI doesn't just transcribe — it understands. It processes the audio, identifies context, separates key discussions from filler, and generates truly meaningful summaries." },
            { icon: 'length', title: 'Works with Any Recording Length', body: "Whether it's a short 5-minute voice memo or a 3-hour conference recording, our AI audio summarizer handles files of any length and delivers a comprehensive summary." },
            { icon: 'lang', title: 'Supports Multiple Languages', body: 'Our AI audio summarizer can process and summarize audio recordings in multiple languages, making it a versatile tool for users working with content worldwide.' },
            { icon: 'star', title: '100% Free with No Sign-Up', body: 'Use our AI audio summarizer at no cost. Upload and summarize as many audio files as you need without hidden fees, subscriptions, or account creation.' },
        ],
        whoBenefitsTitle: 'AI Audio Summarizer',
        whoBenefits: [
            { title: 'Students and Educators', body: 'Summarize recorded lectures, audio textbooks, and educational podcasts to create quick, effective study notes and revision materials.' },
            { title: 'Business Professionals', body: 'Get concise summaries of meeting recordings, conference calls, and voicemail messages to stay aligned and productive without replaying.' },
            { title: 'Podcast Listeners', body: 'Summarize podcast episodes to quickly review key highlights and decide which episodes deserve a full listen before committing your time.' },
            { title: 'Journalists & Media Professionals', body: 'Extract key details from interview recordings, press briefings, and field audio to speed up your reporting and content creation workflow.' },
            { title: 'Researchers and Academics', body: 'Summarize recorded focus groups, research interviews, and audio data to accelerate qualitative analysis and documentation processes.' },
            { title: 'Legal Professionals', body: 'Summarize depositions, recorded testimonies, and client calls to identify critical information and key details quickly and efficiently.' },
        ],
        faqs: [
            { q: 'What audio formats does the summarizer support?', a: 'MP3, WAV, M4A, OGG, FLAC, and WEBM files, up to 10MB per upload.' },
            { q: 'Can I summarize long audio recordings?', a: 'Files are capped at 10MB to keep transcription fast — that is roughly 10-15 minutes of typical voice recording, depending on quality and format.' },
            { q: 'Does it work with podcast episodes?', a: 'Yes, as long as the episode file fits within the 10MB limit — for longer episodes, try a shorter clip or the highlight you want summarized.' },
            { q: 'Is the AI audio summarizer free?', a: 'Yes — audio transcription and summarization is included in your normal plan credits, same as text and document summaries.' },
            { q: 'How accurate is the transcription?', a: "Transcription is powered by Groq's Whisper model, which handles clear speech well; heavy background noise or overlapping speakers can reduce accuracy." },
            { q: 'How is this different from the Video Summarizer?', a: 'Audio uploads are transcribed directly; video files will need their audio track extracted first once that feature ships — audio is the simpler, already-live version of the same idea.' },
        ],
    },
}
