import { Helmet } from 'react-helmet-async'
import MarketingLayout from './MarketingLayout.jsx'

const SUPPORT_EMAIL = 'faizankhan901152@gmail.com'

const TermsOfService = () => (
    <MarketingLayout>
        <Helmet><title>Terms of Service — Notewise</title></Helmet>

        <div className="max-w-3xl mx-auto px-6 py-20">
            <h1 className="font-display text-3xl md:text-4xl font-semibold text-richblack-5 mb-2">Terms of Service</h1>
            <p className="text-richblack-400 text-sm mb-12">Last updated {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

            <div className="space-y-8 text-richblack-200 leading-relaxed">
                <section>
                    <h2 className="text-richblack-5 font-semibold text-lg mb-2">Using Notewise</h2>
                    <p>
                        Notewise lets you summarize text, documents, articles, and audio, and generate flashcards,
                        quizzes, and chat with your notes. You're responsible for the content you submit — don't upload
                        anything you don't have the right to use, or anything illegal, harmful, or abusive.
                    </p>
                </section>

                <section>
                    <h2 className="text-richblack-5 font-semibold text-lg mb-2">Plans and credits</h2>
                    <p>
                        Basic is free and includes a limited number of monthly credits. Pro and Pro Max are paid
                        subscriptions billed monthly, with higher credit allowances. Credit packs are
                        one-time purchases that add credits to your account on top of your plan's monthly allowance.
                    </p>
                </section>

                <section>
                    <h2 className="text-richblack-5 font-semibold text-lg mb-2">Payments and refunds</h2>
                    <p>
                        All payments — subscription charges and credit pack purchases — are final and non-refundable.
                        By upgrading your plan or purchasing a credit pack, you agree that no refund will be issued for
                        that charge, including for partially used billing periods or unused credits. You can cancel a
                        subscription at any time to stop future charges; the current billing period remains active and
                        non-refundable until it ends.
                    </p>
                </section>

                <section>
                    <h2 className="text-richblack-5 font-semibold text-lg mb-2">AI-generated content</h2>
                    <p>
                        Summaries, flashcards, quizzes, and chat responses are generated by AI based on the content you
                        provide. They may occasionally be inaccurate or incomplete. Notewise is a study aid, not a
                        substitute for verifying important information against the original source.
                    </p>
                </section>

                <section>
                    <h2 className="text-richblack-5 font-semibold text-lg mb-2">Account termination</h2>
                    <p>
                        We may suspend or ban accounts that abuse the service, violate these terms, or engage in
                        illegal activity. You may delete your account at any time from Account settings.
                    </p>
                </section>

                <section>
                    <h2 className="text-richblack-5 font-semibold text-lg mb-2">Changes to these terms</h2>
                    <p>
                        We may update these terms as the product changes. Continued use of Notewise after an update
                        means you accept the revised terms.
                    </p>
                </section>

                <section>
                    <h2 className="text-richblack-5 font-semibold text-lg mb-2">Contact</h2>
                    <p>
                        Questions about these terms? Email us at{' '}
                        <a href={`mailto:${SUPPORT_EMAIL}`} className="text-yellow-50 hover:underline">{SUPPORT_EMAIL}</a>.
                    </p>
                </section>
            </div>
        </div>
    </MarketingLayout>
)

export default TermsOfService
